export enum ErrorCodeK {
    E401 = '401',
    E403 = '403',
    E404 = '404',
    E409 = '409',
    E500 = '500',
    ActiveDirectoryNewUserIsNotAcceptable = 'ActiveDirectoryNewUserIsNotAcceptable',
    ActiveDirectoryNewPasswordIsNotAcceptable = 'ActiveDirectoryNewPasswordIsNotAcceptable',
    ActiveDirectoryUserAlreadyExists = 'ActiveDirectoryUserAlreadyExists',
    ActiveDirectoryDealerNotFound = 'ActiveDirectoryDealerNotFound',
    ActiveDirectoryDealerIsFromAnotherCanton = 'ActiveDirectoryDealerIsFromAnotherCanton',
    ActiveDirectoryNewUserWasNotCreated = 'ActiveDirectoryNewUserWasNotCreated',
    ActiveDirectoryNewDealerInvalidInputModel = 'ActiveDirectoryNewDealerInvalidInputModel',
    ActiveDirectoryDealerAlreadyExists = 'ActiveDirectoryDealerAlreadyExists',
    ActiveDirectoryNewDealerWasNotCreated = 'ActiveDirectoryNewDealerWasNotCreated',
    ActiveDirectoryChangePasswordIsNotAcceptable = 'ActiveDirectoryChangePasswordIsNotAcceptable',
    ActiveDirectoryNewPasswordsNotIdentical = 'ActiveDirectoryNewPasswordsNotIdentical',
    ActiveDirectoryCurrentAndNewPasswordsAreIdentical = 'ActiveDirectoryCurrentAndNewPasswordsAreIdentical',
    ActiveDirectoryPasswordWasNotChanged = 'ActiveDirectoryPasswordWasNotChanged',
    ActiveDirectoryChangePasswordInvalidInputModel = 'ActiveDirectoryChangePasswordInvalidInputModel',
    V09ResponseDataError = 'V09ResponseDataError',
    V09ResponseDataValidationError = 'V09ResponseDataValidationError',
    V09ServiceError = 'V09ServiceError',
    V09ServiceNotAvailable = 'V09ServiceNotAvailable'
}
